name: "DEV DEPLOY"

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: dev
      aws-assume-role-arn: "arn:aws:iam::140023394758:role/github-actions-wendel-lopes-fiap-pipeline"
      aws-region: "us-east-2"
      aws-statefile-s3-bucket: "site-wendel"
      aws-lock-dynamodb-table: "wendel-tabela"